import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NavigationMenu } from "@radix-ui/react-navigation-menu";
import Image from "next/image";
import Navbara from "./Components/Navbara"; // Ensure this path is correct
import Background from "./Components/Background"; // Ensure this path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "todolista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className+' bg-slate-100'} >
      {/* <Background/> */}
        <Navbara /> {/* Ensure this is correctly placed */}
        {children}
        
        <h1 className='fixed bottom-5 right-5 text-gray-300'>&copy; Made by Karim Zaafrani</h1>
        
      </body>
    </html>
  );
}